export const LenderList = [
  { value: "ACCORD_MORTGAGES", label: "Accord Mortgages" },
  { value: "AHLI_UNITED_BANK", label: "Ahli United Bank" },
  { value: "AL_RAYAN_BANK", label: "Al Rayan Bank" },
  { value: "ALDERMORE_MORTGAGES", label: "Aldermore Mortgages" },
  { value: "AMICUS_PLC", label: "Amicus PLC" },
  { value: "ASSETZ_CAPITAL", label: "Assetz Capital" },
  { value: "ATOM_BANK", label: "Atom Bank" },
  { value: "AVIVA_EQUITY_RELEASE", label: "Aviva Equity Release" },
  { value: "AXIS_BANK", label: "Axis Bank" },
  { value: "BANK_AND_CLIENTS_PLC", label: "Bank & Clients PLC" },
  { value: "BANK_OF_CHINA", label: "Bank of China" },
  { value: "BANK_OF_CYPRUS_UK", label: "Bank of Cyprus UK" },
  { value: "BANK_OF_IRELAND", label: "Bank of Ireland" },
  { value: "BARCLAYS", label: "Barclays" },
  { value: "BARCLAYS_COMMERCIAL", label: "Barclays Commercial" },
  { value: "BATH_BUILDING_SOCIETY", label: "Bath Building Society" },
  { value: "BEVERLEY_BUILDING_SOCIETY", label: "Beverley Building Society" },
  { value: "BLUESTONE_MORTGAGES", label: "Bluestone Mortgages" },
  { value: "BLUEZEST", label: "BlueZest" },
  { value: "BM_SOLUTIONS", label: "BM Solutions" },
  { value: "BOOST_CAPITAL", label: "Boost Capital" },
  { value: "BRIDGEWATER_EQUITY_RELEASE", label: "Bridgewater Equity Release" },
  {
    value: "BUCKINGHAMSHIRE_BUILDING_SOCIETY",
    label: "Buckinghamshire Building Society",
  },
  {
    value: "CAMBRIDGE_AND_COUNTIES_BANK",
    label: "Cambridge and Counties Bank",
  },
  { value: "CAMBRIDGE_BUILDING_SOCIETY", label: "Cambridge Building Society" },
  { value: "CENTRAL_TRUST", label: "Central Trust" },
  { value: "CHARTERBANK", label: "Charterbank" },
  { value: "CHL_MORTGAGES", label: "CHL Mortgages" },
  {
    value: "CHORLEY_DISTRICT_BUILDING_SOCIETY",
    label: "Chorley & District Building Society",
  },
  { value: "CLEARLY_LOANS", label: "Clearly Loans" },
  { value: "COUTTS", label: "Coutts" },
  { value: "COVENTRY_BUILDING_SOCIETY", label: "Coventry Building Society" },
  { value: "CROWN_EQUITY_RELEASE", label: "Crown Equity Release" },
  {
    value: "CUMBERLAND_BUILDING_SOCIETY",
    label: "Cumberland Building Society",
  },
  { value: "DANSKE_BANK", label: "Danske Bank" },
  {
    value: "DARLINGTON_BUILDING_SOCIETY",
    label: "Darlington Building Society",
  },
  { value: "DIGITAL_MORTGAGES", label: "Digital Mortgages" },
  { value: "DUDLEY_BUILDING_SOCIETY", label: "Dudley Building Society" },
  {
    value: "EARL_SHILTON_BUILDING_SOCIETY",
    label: "Earl Shilton Building Society",
  },
  { value: "ECOLOGY_BUILDING_SOCIETY", label: "Ecology Building Society" },
  { value: "EQUIFINANCE", label: "Equifinance" },
  { value: "FAMILY_BUILDING_SOCIETY", label: "Family Building Society" },
  { value: "FINSEC", label: "FinSec" },
  { value: "FIRST_TRUST_BANK", label: "First Trust Bank" },
  { value: "FLEET_MORTGAGES", label: "Fleet Mortgages" },
  { value: "FOUNDATION_HOME_LOANS", label: "Foundation Home Loans" },
  { value: "FURNESS_BUILDING_SOCIETY", label: "Furness Building Society" },
  { value: "GATEHOUSE_BANK", label: "Gatehouse Bank" },
  { value: "GENERATION_HOME", label: "Generation Home" },
  { value: "GODIVA_MORTGAGES", label: "Godiva Mortgages" },
  { value: "HALIFAX", label: "Halifax" },
  { value: "HAMPSHIRE_TRUST_BANK", label: "Hampshire Trust Bank" },
  { value: "HANDELSBANKEN", label: "Handelsbanken" },
  {
    value: "HANLEY_ECONOMIC_BUILDING_SOCIETY",
    label: "Hanley Economic Building Society",
  },
  { value: "HARPDEN_BUILDING_SOCIETY", label: "Harpenden Building Society" },
  { value: "HSBC", label: "HSBC" },
  { value: "ICICI_BANK", label: "ICICI Bank" },
  { value: "INTERBAY_COMMERCIAL", label: "Interbay Commercial" },
  { value: "INVESTEC", label: "Investec" },
  { value: "IPSWICH_BUILDING_SOCIETY", label: "Ipswich Building Society" },
  { value: "JUST_RETIREMENT_SOLUTIONS", label: "Just Retirement Solutions" },
  { value: "KENSINGTON_MORTGAGES", label: "Kensington Mortgages" },
  { value: "KENT_RELIANCE", label: "Kent Reliance" },
  { value: "KEYSTONE_PROPERTY_FINANCE", label: "Keystone Property Finance" },
  { value: "LEEDS_BUILDING_SOCIETY", label: "Leeds Building Society" },
  {
    value: "LEEK_UNITED_BUILDING_SOCIETY",
    label: "Leek United Building Society",
  },
  { value: "METRO_BANK", label: "Metro Bank" },
  {
    value: "MONMOUTHSHIRE_BUILDING_SOCIETY",
    label: "Monmouthshire Building Society",
  },
  { value: "NATIONWIDE", label: "Nationwide" },
  { value: "NATWEST", label: "NatWest" },
  {
    value: "NOTTINGHAM_BUILDING_SOCIETY",
    label: "Nottingham Building Society",
  },
  { value: "PARAGON_MORTGAGES", label: "Paragon Mortgages" },
  { value: "PEPPER_MONEY", label: "Pepper Money" },
  { value: "POST_OFFICE_MORTGAGES", label: "Post Office Mortgages" },
  {
    value: "PRINCIPALITY_BUILDING_SOCIETY",
    label: "Principality Building Society",
  },
  { value: "SANTANDER", label: "Santander" },
  { value: "SKIPTON_BUILDING_SOCIETY", label: "Skipton Building Society" },
  { value: "TSB", label: "TSB" },
  { value: "ULSTER_BANK", label: "Ulster Bank" },
  { value: "UNKNOWN", label: "Unknown" },
  { value: "VIDA_HOMELOANS", label: "Vida Homeloans" },
  {
    value: "WEST_BROMWICH_BUILDING_SOCIETY",
    label: "West Bromwich Building Society",
  },
  { value: "WEST_ONE_LOANS", label: "West One Loans" },
  { value: "OTHER", label: "Other" },
];

export default LenderList;
