export const LenderList = [
  { value: "ACCORD_MORTGAGES", label: "Accord Mortgages" },
  { value: "AHLI_UNITED_BANK", label: "Ahli United Bank" },
  { value: "AL_RAYAN_BANK", label: "Al Rayan Bank" },
  { value: "ALDERMORE_MORTGAGES", label: "Aldermore Mortgages" },
  { value: "AMICUS_PLC", label: "Amicus PLC" },
  { value: "ASSETZ_CAPITAL", label: "Assetz Capital" },
  { value: "ATOM_BANK", label: "Atom Bank" },
  { value: "AVIVA_EQUITY_RELEASE", label: "Aviva Equity Release" },
  { value: "AXIS_BANK", label: "Axis Bank" },
  { value: "BANK_AND_CLIENTS_PLC", label: "Bank & Clients PLC" },
  { value: "BANK_OF_CHINA", label: "Bank of China" },
  { value: "BANK_OF_CYPRUS_UK", label: "Bank of Cyprus UK" },
  { value: "BANK_OF_IRELAND", label: "Bank of Ireland" },
  { value: "BARCLAYS", label: "Barclays" },
  { value: "BARCLAYS_COMMERCIAL", label: "Barclays Commercial" },
  { value: "BATH_BUILDING_SOCIETY", label: "Bath Building Society" },
  { value: "BEVERLEY_BUILDING_SOCIETY", label: "Beverley Building Society" },
  { value: "BLUESTONE_MORTGAGES", label: "Bluestone Mortgages" },
  { value: "BLUEZEST", label: "BlueZest" },
  { value: "BM_SOLUTIONS", label: "BM Solutions" },
  { value: "BOOST_CAPITAL", label: "Boost Capital" },
  { value: "BRIDGEWATER_EQUITY_RELEASE", label: "Bridgewater Equity Release" },
  {
    value: "BUCKINGHAMSHIRE_BUILDING_SOCIETY",
    label: "Buckinghamshire Building Society",
  },
  {
    value: "CAMBRIDGE_AND_COUNTIES_BANK",
    label: "Cambridge and Counties Bank",
  },
  { value: "CAMBRIDGE_BUILDING_SOCIETY", label: "Cambridge Building Society" },
  { value: "CENTRAL_TRUST", label: "Central Trust" },
  { value: "CHARTERBANK", label: "Charterbank" },
  { value: "CHL_MORTGAGES", label: "CHL Mortgages" },
  {
    value: "CHORLEY_DISTRICT_BUILDING_SOCIETY",
    label: "Chorley & District Building Society",
  },
  { value: "CLEARLY_LOANS", label: "Clearly Loans" },
  { value: "COUTTS", label: "Coutts" },
  { value: "COVENTRY_BUILDING_SOCIETY", label: "Coventry Building Society" },
  { value: "CROWN_EQUITY_RELEASE", label: "Crown Equity Release" },
  {
    value: "CUMBERLAND_BUILDING_SOCIETY",
    label: "Cumberland Building Society",
  },
  { value: "DANSKE_BANK", label: "Danske Bank" },
  {
    value: "DARLINGTON_BUILDING_SOCIETY",
    label: "Darlington Building Society",
  },
  { value: "DIGITAL_MORTGAGES", label: "Digital Mortgages" },
  { value: "DUDLEY_BUILDING_SOCIETY", label: "Dudley Building Society" },
  {
    value: "EARL_SHILTON_BUILDING_SOCIETY",
    label: "Earl Shilton Building Society",
  },
  { value: "ECOLOGY_BUILDING_SOCIETY", label: "Ecology Building Society" },
  { value: "EQUIFINANCE", label: "Equifinance" },
  { value: "FAMILY_BUILDING_SOCIETY", label: "Family Building Society" },
  { value: "FINSEC", label: "FinSec" },
  { value: "FIRST_TRUST_BANK", label: "First Trust Bank" },
  { value: "FLEET_MORTGAGES", label: "Fleet Mortgages" },
  { value: "FOUNDATION_HOME_LOANS", label: "Foundation Home Loans" },
  { value: "FURNESS_BUILDING_SOCIETY", label: "Furness Building Society" },
  { value: "GATEHOUSE_BANK", label: "Gatehouse Bank" },
  { value: "GENERATION_HOME", label: "Generation Home" },
  { value: "GODIVA_MORTGAGES", label: "Godiva Mortgages" },
  { value: "HALIFAX", label: "Halifax" },
  { value: "HAMPSHIRE_TRUST_BANK", label: "Hampshire Trust Bank" },
  { value: "HANDELSBANKEN", label: "Handelsbanken" },
  {
    value: "HANLEY_ECONOMIC_BUILDING_SOCIETY",
    label: "Hanley Economic Building Society",
  },
  { value: "HARPDEN_BUILDING_SOCIETY", label: "Harpenden Building Society" },
  {
    value: "HINCKLEY_AND_RUGBY_BUILDING_SOCIETY",
    label: "Hinckley and Rugby Building Society",
  },
  { value: "HODGE_BANK", label: "Hodge Bank" },
  { value: "HODGE_LIFETIME", label: "Hodge Lifetime" },
  {
    value: "HOLMESDALE_BUILDING_SOCIETY",
    label: "Holmesdale Building Society",
  },
  { value: "HSBC", label: "HSBC" },
  { value: "ICICI_BANK", label: "ICICI Bank" },
  { value: "INTERBAY_COMMERCIAL", label: "Interbay Commercial" },
  { value: "INVESTEC", label: "Investec" },
  { value: "IPSWICH_BUILDING_SOCIETY", label: "Ipswich Building Society" },
  { value: "JUST_RETIREMENT_SOLUTIONS", label: "Just Retirement Solutions" },
  { value: "KENSINGTON_MORTGAGES", label: "Kensington Mortgages" },
  { value: "KENT_RELIANCE", label: "Kent Reliance" },
  { value: "KEYSTONE_PROPERTY_FINANCE", label: "Keystone Property Finance" },
  { value: "LANDBAY", label: "Landbay" },
  { value: "LEEDS_BUILDING_SOCIETY", label: "Leeds Building Society" },
  {
    value: "LEEK_UNITED_BUILDING_SOCIETY",
    label: "Leek United Building Society",
  },
  {
    value: "LEGAL_AND_GENERAL_HOME_FINANCE",
    label: "Legal and General Home Finance",
  },
  { value: "LENDINVEST", label: "LendInvest" },
  { value: "LLOYDS_COMMERCIAL", label: "Lloyds Commercial" },
  { value: "LV", label: "LV" },
  { value: "MAGELLAN_HOMELOANS", label: "Magellan Homeloans" },
  { value: "MANSFIELD_BUILDING_SOCIETY", label: "Mansfield Building Society" },
  {
    value: "MARKET_HARBOROUGH_BUILDING_SOCIETY",
    label: "Market Harborough Building Society",
  },
  { value: "MARSDEN_BUILDING_SOCIETY", label: "Marsden Building Society" },
  { value: "MASTHAVEN_BANK", label: "Masthaven Bank" },
  { value: "MBS_LENDING_LTD", label: "MBS Lending Ltd" },
  { value: "METRO_BANK", label: "Metro Bank" },
  { value: "MOLO_FINANCE", label: "Molo Finance" },
  {
    value: "MONMOUTHSHIRE_BUILDING_SOCIETY",
    label: "Monmouthshire Building Society",
  },
  { value: "MORE_2_LIFE_LIMITED", label: "more 2 life Limited" },
  { value: "N_AND_P_COMMERCIAL", label: "N&P Commercial" },
  { value: "NATIONWIDE", label: "Nationwide" },
  { value: "NATWEST", label: "NatWest" },
  {
    value: "NATWEST_INTERMEDIARY_SOLUTIONS",
    label: "Natwest Intermediary Solutions",
  },
  { value: "NATWEST_INTERNATIONAL", label: "Natwest International" },
  { value: "NEW_STREET_MORTGAGES", label: "New Street Mortgages" },
  { value: "NEWBURY_BUILDING_SOCIETY", label: "Newbury Building Society" },
  { value: "NEWCASTLE_BUILDING_SOCIETY", label: "Newcastle Building Society" },
  { value: "NORTON_FINANCE", label: "Norton Finance" },
  {
    value: "NOTTINGHAM_BUILDING_SOCIETY",
    label: "Nottingham Building Society",
  },
  { value: "NUCLEUS_COMMERCIAL", label: "Nucleus Commercial" },
  { value: "OFFA", label: "Offa" },
  { value: "OMNI_CAPITAL", label: "Omni Capital" },
  {
    value: "ONEFAMILY_LIFETIME_MORTGAGES",
    label: "OneFamily Lifetime Mortgages",
  },
  { value: "OPLO", label: "Oplo" },
  { value: "OPTIMUM_CREDIT", label: "Optimum Credit" },
  { value: "PARAGON_MORTGAGES", label: "Paragon Mortgages" },
  { value: "PEPPER_MONEY", label: "Pepper Money" },
  { value: "PLATFORM", label: "Platform" },
  { value: "POST_OFFICE_MORTGAGES", label: "Post Office Mortgages" },
  { value: "PRECISE_MORTGAGES", label: "Precise Mortgages" },
  { value: "PRESTIGE_FINANCE", label: "Prestige Finance" },
  {
    value: "PRINCIPALITY_BUILDING_SOCIETY",
    label: "Principality Building Society",
  },
  {
    value: "PROGRESSIVE_BUILDING_SOCIETY",
    label: "Progressive Building Society",
  },
  { value: "PURE_RETIREMENT", label: "Pure Retirement" },
  { value: "SAFFRON_BUILDING_SOCIETY", label: "Saffron Building Society" },
  { value: "SAINSBURYS_BANK", label: "Sainsbury's Bank" },
  { value: "SANTANDER", label: "Santander" },
  { value: "SCOTTISH_BUILDING_SOCIETY", label: "Scottish Building Society" },
  { value: "SCOTTISH_WIDOWS", label: "Scottish Widows" },
  { value: "SECURE_TRUST_BANK", label: "Secure Trust Bank" },
  { value: "SHAWBROOK_BANK", label: "Shawbrook Bank" },
  { value: "SKIPTON_BUILDING_SOCIETY", label: "Skipton Building Society" },
  { value: "SKIPTON_INTERNATIONAL", label: "Skipton International" },
  { value: "SPRING_FINANCE", label: "Spring Finance" },
  {
    value: "STAFFORD_RAILWAY_BUILDING_SOCIETY",
    label: "Stafford Railway Building Society",
  },
  { value: "STATE_BANK_OF_INDIA_UK", label: "State Bank of India UK" },
  { value: "STEP_ONE_FINANCE", label: "Step One Finance" },
  { value: "STRIDE_UP", label: "Stride Up" },
  { value: "SUFFOLK_BUILDING_SOCIETY", label: "Suffolk Building Society" },
  { value: "SWANSEA_BUILDING_SOCIETY", label: "Swansea Building Society" },
  { value: "TANDEM_HOME_LOANS", label: "Tandem Home Loans" },
  { value: "TEACHERS_BUILDING_SOCIETY", label: "Teachers Building Society" },
  { value: "TESCO_BANK", label: "Tesco Bank" },
  {
    value: "THE_MELTON_BUILDING_SOCIETY",
    label: "The Melton Building Society",
  },
  { value: "THE_MORTGAGE_LENDER", label: "The Mortgage Lender" },
  { value: "THE_MORTGAGE_WORKS", label: "The Mortgage Works" },
  {
    value: "TIPTON_AND_COSELEY_BUILDING_SOCIETY",
    label: "Tipton & Coseley Building Society",
  },
  { value: "TOGETHER_MONEY", label: "Together Money" },
  { value: "TSB", label: "TSB" },
  { value: "ULSTER_BANK", label: "Ulster Bank" },
  { value: "UNKNOWN", label: "Unknown" },
  { value: "UNITED_TRUST_BANK", label: "United Trust Bank" },
  { value: "VERNON_BUILDING_SOCIETY", label: "Vernon Building Society" },
  { value: "VIDA_HOMELOANS", label: "Vida Homeloans" },
  {
    value: "WEST_BROMWICH_BUILDING_SOCIETY",
    label: "West Bromwich Building Society",
  },
  { value: "WEST_ONE_LOANS", label: "West One Loans" },
  { value: "OTHER", label: "Other" },
];

export default LenderList;
