export interface EmploymentDetailsProps {
  alias: string;
  user: {
    id: number;
    alias: string;
    email: string;
    phone: string;
    title: string | null;
    first_name: string;
    middle_name: string | null;
    last_name: string;
    profile_image: string | null;
    user_type: string;
  };
  employment_status: string;
  employment_type: string | null;
  occupation: string | null;
  industry: string | null;
  employer_name: string | null;
  employer_telephone: string | null;
  employer_name_for_reference: string | null;
  employer_email_for_reference: string | null;
  employer_postcode: string | null;
  employer_house_name_or_number: string | null;
  employer_address_line_1: string | null;
  employer_address_line_2: string | null;
  employer_city: string | null;
  employer_county: string | null;
  employer_country: string | null;
  employer_latitude?: number | null;
  employer_longitude?: number | null;
  employment_commenced: string | null;
  employment_ended: string | null;
  gross_monthly_income: number | null;
  net_monthly_income: number | null;
  is_probationary_period: boolean;
  is_income_in_foreign_currency: boolean;
  further_details: number | null;
  bonus: number | null;
  is_bonus_guaranteed: boolean;
  bonus_frequency: string | null;
  overtime: number | null;
  is_overtime_guaranteed: boolean;
  overtime_frequency: string | null;
  allowance: number | null;
  is_allowance_guaranteed: boolean;
  allowance_frequency: string | null;
  employment_time_year: number | null;
  employment_time_month: number | null;
  business_telephone: string | null;
  business_house_name_or_number: string | null;
  business_postcode: string | null;
  business_address_line_1: string | null;
  business_address_line_2: string | null;
  business_city: string | null;
  business_county: string | null;
  business_country: string | null;
  business_latitude?: number | null;
  business_longitude?: number | null;
  job_title: string | null;
  business_name: string | null;
  business_type: string | null;
  percentage_of_business_owned: string | null;
  is_accounts_available: boolean;
  accountant_name: string | null;
  accountant_qualifications: string | null;
  salary: number | null;
  dividends: number | null;
  turnover: number | null;
  income_source: string | null;
  other_income: number | null;
  other_income_source: string | null;
  other: string | null;
  other_income_start_date: string | null;
  contractor_industry: string | null;
  current_contract_start: string | null;
  current_contract_end: string | null;
  time_contracting: string | null;
  day_rate: number | null;
  hourly_rate: number | null;
  note: string | null;
  year1: string | null;
  year1_net_profit: number | null;
  year2: string | null;
  year2_net_profit: number | null;
  year3: string | null;
  year3_net_profit: number | null;
}

export interface EmploymentTabContentProps {
  activeTab: string | null;
  activeUser: number | null;
  groupedData: Record<number, EmploymentDetailsProps[]>;
}

export interface AddEmploymentDetailsModalProps {
  isOpen: boolean;
  toggle: () => void;
  employmentData: EmploymentDetailsProps | null;
  groupedData?: Record<number, EmploymentDetailsProps[]>;
}
